# Docker Compose override para desenvolvimento local
# Use: docker compose -f docker-compose.yml -f docker-compose.local.yml up -d
# Ou simplesmente use o deploy.sh script

version: '3.8'

services:
  job-matching-api:
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  grafana:
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    networks:
      - monitoring

  loki:
    ports:
      - "3100:3100"
    networks:
      - monitoring

  promtail:
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
