server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: job-matching-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: job-matching-api-logs
          __path__: /var/log/app/*.log
    pipeline_stages:
      - match:
          selector: '{job="job-matching-api-logs"}'
          stages:
            - json:
                expressions:
                  timestamp: timestamp
                  level: level
                  message: message
            - timestamp:
                source: timestamp
                format: RFC3339